version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"